### ISSUE TITLE
안녕하세요 제가 git 사용법을 아직 잘몰라서 당분간은 웹상에서 업로드 하겠습니다

### ISSUE THREAD

**Issue by gwanggyoipark** [hjaka08/web-NYHC-markdown#1]
안녕하세요 
제가 git 사용법을 아직 잘몰라서 당분간은 웹상에서 업로드 하겠습니다
감사합니다.

**Comment by hjaka08** [comment]
안녕하세요 안현준입니다.

git 사용법을 모르시면 웹상에서 업로드 하셔도 됩니다..

단 제가 주기적으로 업로드하신내용을 내려받기해서 커밋을 다시해서 다시 올리도록 하겠습니다..

감사합니다.
